# Generated by Django 5.2.17 on 2026-08-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetricSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('total_github_trends', 'Total repos trending'), ('avg_stars', 'Media de estrellas (GitHub)'), ('avg_forks', 'Media de forks (GitHub)'), ('total_reddit_posts', 'Total posts Reddit'), ('avg_reddit_score', 'Media de score (Reddit)'), ('avg_reddit_comments', 'Media de comentarios (Reddit)'), ('total_ph_launches', 'Total launches Product Hunt'), ('avg_ph_votes', 'Media de votos (Product Hunt)')], db_index=True, max_length=64, verbose_name='Tipo de métrica')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp (UTC)')),
            ],
            options={
                'ordering': ['-timestamp'],
                'constraints': [models.UniqueConstraint(fields=('metric_type', 'timestamp'), name='uniq_metric_per_timestamp')],
            },
        ),
    ]
