# Generated by Django 5.2.17 on 2026-08-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metricsnapshot',
            name='metric_type',
            field=models.CharField(choices=[('total_github_trends', 'Total repos trending'), ('avg_stars', 'Media de estrellas (GitHub)'), ('avg_forks', 'Media de forks (GitHub)'), ('total_hn_stories', 'Total historias Hacker News'), ('avg_hn_points', 'Media de puntos (Hacker News)'), ('avg_hn_comments', 'Media de comentarios (Hacker News)'), ('total_ph_launches', 'Total launches Product Hunt'), ('avg_ph_votes', 'Media de votos (Product Hunt)')], db_index=True, max_length=64, verbose_name='Tipo de métrica'),
        ),
    ]
