# Generated by Django 5.2.17 on 2026-08-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(db_index=True, max_length=255, verbose_name='Nombre del repo')),
                ('stars', models.PositiveIntegerField(default=0, verbose_name='Estrellas')),
                ('forks', models.PositiveIntegerField(default=0, verbose_name='Forks')),
                ('language', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Lenguaje')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('trending_date', models.DateField(db_index=True, verbose_name='Fecha del trending')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en BD')),
            ],
            options={
                'ordering': ['-trending_date', '-stars'],
                'indexes': [models.Index(fields=['language', 'trending_date'], name='github_lang_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('url', 'trending_date'), name='uniq_github_repo_per_trending_date')],
            },
        ),
    ]
