# Generated by Django 5.2.17 on 2026-08-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HackerNewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn_id', models.IntegerField(unique=True, verbose_name='ID en Hacker News')),
                ('title', models.CharField(max_length=500, verbose_name='Título')),
                ('points', models.IntegerField(default=0, verbose_name='Puntos')),
                ('comments', models.PositiveIntegerField(default=0, verbose_name='Comentarios')),
                ('author', models.CharField(db_index=True, max_length=100, verbose_name='Autor')),
                ('url', models.URLField(blank=True, default='', max_length=1000, verbose_name='URL')),
                ('created_at', models.DateTimeField(db_index=True, verbose_name='Fecha de la historia (UTC)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='Capturado en BD')),
            ],
            options={
                'ordering': ['-created_at', '-points'],
                'indexes': [models.Index(fields=['author', 'created_at'], name='hn_author_created_idx'), models.Index(fields=['points'], name='hn_points_idx')],
            },
        ),
    ]
