# Generated by Django 5.2.17 on 2026-08-15 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHuntLaunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Nombre del producto')),
                ('tagline', models.TextField(blank=True, null=True, verbose_name='Tagline')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Votos')),
                ('url', models.URLField(max_length=500, unique=True, verbose_name='URL')),
                ('launch_date', models.DateField(db_index=True, verbose_name='Fecha de lanzamiento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en BD')),
            ],
            options={
                'ordering': ['-launch_date', '-votes'],
                'indexes': [models.Index(fields=['launch_date', 'votes'], name='ph_date_votes_idx')],
            },
        ),
    ]
